server:
  port: 8800
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lowering
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    open-in-view: true
    show-sql: true


